//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BralmerBioscopen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BralmerDatabaseEntities : DbContext
    {
        public BralmerDatabaseEntities()
            : base("name=BralmerDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<film> films { get; set; }
        public virtual DbSet<filmdraai> filmdraais { get; set; }
        public virtual DbSet<gast> gasts { get; set; }
        public virtual DbSet<korting> kortings { get; set; }
        public virtual DbSet<reservering> reserverings { get; set; }
        public virtual DbSet<zaal> zaals { get; set; }
    }
}
