//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BralmerBioscopen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmdraai
    {
        public filmdraai()
        {
            this.reserverings = new HashSet<reservering>();
        }
    
        public string idFilmdraai { get; set; }
        public int Film_idFilm { get; set; }
        public int Zaal_idZaal { get; set; }
        public System.DateTime Begintijd { get; set; }
        public System.DateTime Eindtijd { get; set; }
        public double Filmdraaiprijs { get; set; }
    
        public virtual ICollection<reservering> reserverings { get; set; }
        public virtual film film { get; set; }
        public virtual zaal zaal { get; set; }
    }
}
