//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BralmerBioscopen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gast
    {
        public int idGast { get; set; }
        public Nullable<int> Reservering_idReservering { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Tussenvoegsels { get; set; }
    
        public virtual reservering reservering { get; set; }
    }
}
