//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BralmerBioscopen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class korting
    {
        public int idKorting { get; set; }
        public System.DateTime Begindatum { get; set; }
        public System.DateTime Einddatum { get; set; }
        public int KortingProcent { get; set; }
    
        public virtual reservering reservering { get; set; }
    }
}
