//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BralmerBioscopen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservering
    {
        public reservering()
        {
            this.gasts = new HashSet<gast>();
            this.kortings = new HashSet<korting>();
        }
    
        public int idReservering { get; set; }
        public string Filmdraai_idFilmdraai { get; set; }
        public int AantalGasten { get; set; }
        public string TotaalPrijs { get; set; }
        public double Reserveringcol { get; set; }
        public string Postcode { get; set; }
        public int Huisnummer { get; set; }
        public string BankrekeningNummer { get; set; }
        public int Gast_idGast { get; set; }
        public Nullable<int> Korting_idKorting { get; set; }
    
        public virtual ICollection<gast> gasts { get; set; }
        public virtual ICollection<korting> kortings { get; set; }
        public virtual filmdraai filmdraai { get; set; }
    }
}
