//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BralmerBioscopen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaal
    {
        public zaal()
        {
            this.filmdraais = new HashSet<filmdraai>();
        }
    
        public int idZaal { get; set; }
        public string Naam { get; set; }
        public int Zitplaatsen { get; set; }
    
        public virtual ICollection<filmdraai> filmdraais { get; set; }
    }
}
